version: "3.8"
services:
  backend:
    build: ./server
    restart: unless-stopped
    environment:
      PORT: 4001
      JWT_SECRET: "troque_por_uma_chave_secreta_forte"
      SQLITE_FILE: /data/fusion.db
    volumes:
      - ./server/data:/data
      - ./server/uploads:/usr/src/app/uploads
    ports:
      - "4001:4001"

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "3001:80"
